version: '2' 
services:
  livy:
    image: hadoop-livy
    container_name: hadoop-livy
    ports:
      - 9870:9870
      - 9864:9864
      - 8088:8088
      - 8042:8042
      - 19888:19888
      - 8998:8998
      
  notebook:
    image: notebook
    container_name: notebook
    ports:
      - 8000:8000